# "Tensorflow Fundamentals"

- badges: true
- comments: true
- categories: [machine_learning, tensorflow]
- hide: false
- author: Atiq Urrehaman
- search_exclude: false

In [16]:
# Import Tensorflow

import tensorflow as tf

print(tf.__version__)

2.6.0


In [17]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [18]:
# Check the number of dimension of a tensors(ndim stands for number of dimensions)
scalar.ndim

0

In [19]:
# Create a vector

vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [20]:
# Check the dimension of our vector
vector.ndim

1

In [21]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                            [7, 10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [22]:
# Dimension of the matrix

matrix.ndim

2

In [23]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                                    [3., 2.],
                                    [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [24]:
# What's the number of dimension of another_matrix?
another_matrix.ndim

2

In [25]:
# Let create a tensor

tensor = tf.constant(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ],
        [
            [13, 14, 15],
            [16, 17, 18]
        ]
    ]
)

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [26]:
tensor.ndim

3

In [27]:
# Creating tensor with Variable

tf.Variable

tensorflow.python.ops.variables.Variable

In [28]:
changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])

changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [29]:
# Lets try change one of the elements in our changable tensor
changeable_tensor[0] = 7
changeable_tensor

NameError: name 'changeable_tensor' is not defined

In [ ]:
# How about we try .assign()

changable_tensor[0].assign(7)
changable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [ ]:
# Let's try change our un-changable tensor

unchangable_tensor[0].assign(7)
unchangable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
# Creating two a random nubmer

random_1 = tf.random.Generator.from_seed(42) # Set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2)) # probability is constant

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?

random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements i a tensors

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent)
not_shuffled = tf.constant(
    [
        [10, 7],
        [3, 4],
        [2, 5]
    ]
)

# Shuffle our non-shuffled tensor

shuffled=tf.random.shuffle(not_shuffled, seed=42, name="Shuffle")

not_shuffled.ndim, shuffled

(2,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 2,  5],
        [ 3,  4],
        [10,  7]])>)

In [ ]:
# Practice for create a random tensor

tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [ ]:
tf.random.set_seed(54)
tf.random.shuffle(not_shuffled)Ak

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

In [ ]:
tf.random.set_seed(54) # global level random seed
tf.random.shuffle(not_shuffled, seed=32) # operation level random seed

NameError: name 'not_shuffled' is not defined