# "Tensorflow Fundamentals"

- badges: true
- comments: true
- categories: [machine_learning, tensorflow]
- hide: false
- author: Atiq Urrehaman
- search_exclude: false

In [1]:
# Import Tensorflow

import tensorflow as tf

print(tf.__version__)

2.6.0


In [2]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimension of a tensors(ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector

vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
# Check the dimension of our vector
vector.ndim

1

In [6]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                            [7, 10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [7]:
# Dimension of the matrix

matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                                    [3., 2.],
                                    [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# What's the number of dimension of another_matrix?
another_matrix.ndim

2

In [10]:
# Let create a tensor

tensor = tf.constant(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ],
        [
            [13, 14, 15],
            [16, 17, 18]
        ]
    ]
)

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [11]:
tensor.ndim

3

In [12]:
# Creating tensor with Variable

tf.Variable

tensorflow.python.ops.variables.Variable

In [13]:
changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])

changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [14]:
%%script echo "TypeError: 'ResourceVariable' object does not support item assignment"

# Lets try change one of the elements in our changable tensor
changable_tensor[0] = 7
changable_tensor

TypeError: 'ResourceVariable' object does not support item assignment


In [15]:
# How about we try .assign()

changable_tensor[0].assign(7)
changable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [16]:
%%script echo "AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'"

# Let's try change our un-changable tensor

unchangable_tensor[0].assign(7)
unchangable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'


In [17]:
# Creating two a random nubmer

random_1 = tf.random.Generator.from_seed(42) # Set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2)) # probability is constant

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?

random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements i a tensors

In [18]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent)
not_shuffled = tf.constant(
    [
        [10, 7],
        [3, 4],
        [2, 5]
    ]
)

# Shuffle our non-shuffled tensor

shuffled=tf.random.shuffle(not_shuffled, seed=42, name="Shuffle")

not_shuffled.ndim, shuffled

(2,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 2,  5],
        [ 3,  4],
        [10,  7]])>)

In [19]:
# Practice for create a random tensor

tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [20]:
tf.random.set_seed(54)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

In [21]:
tf.random.set_seed(54) # global level random seed
tf.random.shuffle(not_shuffled, seed=32) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

### Other ways to make tensors

In [22]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [23]:
# Create a tensors of all zero
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy array into tensors

The main difference between Numpy array and Tensorflow tensors is that tensors can be run on a GPU computing

In [24]:
# You can also turn NumPy arrays into tensors
import numpy as np

numpy_A= np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25.

numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [25]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [26]:
A.ndim

3

### Getting information from tensors

- Shape
- Rank
- Axis or dimension
- Size

#### Tensor Attributes

|Attribute|Meaning|Code|
|---|---|---|
|Shape|The length(number of elements) of each of the dimensions of a tensor|`tensor.shape`|
|Rank|The number of tensor  dimension. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.|`tensor.ndim`|
|Axis or dimension|A particular dimension of a tensor|`tensor[0], tensor[:,1]`|
|Size|The total number of items in the tensor|`tf.size(tensor)`|


In [27]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor, rank_4_tensor.ndim

(<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
 array([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],
 
 
        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]], dtype=float32)>,
 4)

In [28]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [29]:
# Get the various attributes of our tensors

def TensorAttributes(tensor):
    tf.print("Datatypes of every element: ", tensor.dtype)
    tf.print("Number of dimensions (rank): ", tensor.ndim)
    tf.print("Shape of tensor: ", tensor.shape)
    tf.print("Elements along the 0 axis: ", tensor.shape[0])
    tf.print("Elements along the last axis: ", tensor.shape[-1])
    tf.print("Total number of elements in our tensor: ", tf.size(tensor))

TensorAttributes(rank_4_tensor)

Datatypes of every element:  tf.float32
Number of dimensions (rank):  4
Shape of tensor:  TensorShape([2, 3, 4, 5])
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  120


In [31]:
# Get the first element form each dimension from each dex except for the final one
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>